### ISSUE TITLE
Feature request Immersive Engineering - Exchangers

### ISSUE THREAD

**Issue by nmarshall23** [JackyyTV/Exchangers#22]
### Issue type (Crash / Bug report / Suggestion):
Suggestion

### Issue Description:

I'm putting together a modpack without Ender IO, Thermal Expansion or Mekanism.

I'd love to have a RF Exchanger themed for Immersive Engineering.

**Comment by JackyyTV** [comment]
This should be quite easy to do, although my artist is having a holiday at the moment, so it might take a while for me to push the new update with Immersive Engineering exchanger variants.

**Comment by JackyyTV** [comment]
Do apologise it took a bit long for me to work on a new update of Exchangers due to reallife stuff, but the new versions are here:
[1.10.2](https://github.com/Jacky1356400/Exchangers/releases/tag/1.10.2-1.6)
[1.11.2](https://github.com/Jacky1356400/Exchangers/releases/tag/1.11.2-1.6)
[1.12.x](https://github.com/Jacky1356400/Exchangers/releases/tag/1.12-2.5)
