### ISSUE TITLE
Crash on load: 1.12.2

### ISSUE THREAD

**Issue by kragnoth** [JackyyTV/Exchangers#30]
Pastebin link: https://pastebin.com/ARVbn75N
Forge: forge-14.23.0.2515
Exchangers version: Exchangers-1.12-2.5.jar      
Minecraft: 1.12.2

Only happens when I switch recipes from normal to easy.

I'm too tired today after working all day to decipher the bug, requesting assistance if it is an easy fix.  Hoping this is helpful if its a bug on your end. 

edit: Crashes while game is loading.  Does not get to main menu.

Thanks, great mod.

**Comment by JackyyTV** [comment]
Oops, that'd be me derping on the recipes when I was porting the changes from 1.10.2 / 1.11.2 to 1.12, and I am able to reproduce the crash on my side too. I will try and fix it as soon as I can.
As for the recipes, I am doing them inside of Java classes instead of using the standard JSON way, mainly because it's easier to manage and modify than JSON recipes.

**Comment by JackyyTV** [comment]
I've just pushed the new update to CurseForge and it's under review, if you don't want to wait and get the new version early, you can get it here: [click me](https://github.com/Jacky1356400/Exchangers/releases/tag/1.12-2.5.1)

Edit: It's approved now. [Download link](https://minecraft.curseforge.com/projects/exchangers/files/2495191)

**Comment by kragnoth** [comment]
Thanks, loading in to check it out.
