### ISSUE TITLE
[1.12.2] Config for higher mining levels

### ISSUE THREAD

**Issue by NielsPilgaard** [JackyyTV/Exchangers#52]
Hey!

Would it be possible to increase the max mining level config to ~15?
I have custom mining levels up to 14, and it'd be nice to be able to use the Exchangers more.
Reference: NillerMedDild/Enigmatica2Expert#46

**Comment by JackyyTV** [comment]
The harvest level limit has been uncapped to 2147483647 on [2.7.2](https://minecraft.curseforge.com/projects/exchangers/files/2558022).
By default, if you don't localize the harvest level, it'll just show a number to represent the level. You may localize the harvest level using CraftTweaker / ResourceLoader so they show names instead of numbers on the tooltips of each Exchangers.
The language key is: `exchangers.harvest_level.[number]`

**Comment by NielsPilgaard** [comment]
Thank you very much :)
