### ISSUE TITLE
Swapping stairs doesn't retain facing direction

### ISSUE THREAD

**Issue by JakeMoe** [JackyyTV/Exchangers#59]
I've got a wooden stair roof that is getting hit by lightning and getting holes burnt into it.  So I go to swap them out with cobble using an Advanced Exchanger (one of the Mekanism Exchangers), and all the cobble stairs are facing the same direction, instead of retaining the direction the wooden stairs had.

**Comment by JackyyTV** [comment]
This is intentional since the Exchangers are supposed to save the blockstates of the block it's swapping to, but I suppose I could add a feature as a keybind to enable facing-based placements.
(Apologies for the late reply, I am extremely busy with work and I've got loads of stuff going on in real life.)

**Comment by JackyyTV** [comment]
Added a new directional placement mode in [2.9](https://www.curseforge.com/minecraft/mc-mods/exchangers/files/2903998), by default is bound to the apostrophe key. Enable it and you should be able to swap blocks based on where you're facing instead of the saved block states within the exchanger itself.

**Comment by JakeMoe** [comment]
Thank you!  :-)
