### ISSUE TITLE
Exchanger - Exchanging Magma Slimy Grass gives only Purple Slimy Grass instead

### ISSUE THREAD

**Issue by Freebi85** [JackyyTV/Exchangers#60]
When using a diamond exchanger in the Nether to exchange a few Magma Slime Grass blocks they turn into the wrong slime grass blocks; purple slimy grass!

![pic1](https://user-images.githubusercontent.com/42634622/66285861-01591380-e8cf-11e9-9422-ee4aa119c6c3.png)

![pic2](https://user-images.githubusercontent.com/42634622/66285866-04ec9a80-e8cf-11e9-8e62-f5819388481d.png)

**Comment by JackyyTV** [comment]
What version of Exchangers? I'd assume 2.8?

**Comment by Freebi85** [comment]
Yeah Sry my bad^^
Exchangers Version 2.8
Forge .2836

**Comment by Freebi85** [comment]
I am afraid this problem will not be solved in 1.12.2. :/ Gonna close

**Comment by JackyyTV** [comment]
I am really sorry, since I have a job, it is really hard to keep up with Minecraft modding while having so much to do at work. I am still trying my best to work on mod updates as much as I can, but since I have 8 different mods to maintain, things are taking longer than I had originally hoped for. I should have a bit more time to look into that next week since I have a short holiday coming up. Apologies again for the delay.

**Comment by Freebi85** [comment]
Hey there’s  absolutely no need to apologize. We all do it voluntarily and what can I say, life happens :)  It was a small issue anyway. If one day there's time to fix it, that's great. If not, no biggie. 

I still love your mod and it was a good idea to put it in in my modpack ddss 👌💖

**Comment by JackyyTV** [comment]
I've found the issue, it's something to do with my current code of handling silk touch drops, I've fixed it and the fix will be in the next update.

Gonna reopen this issue until I've pushed the changes to GitHub.

**Comment by JackyyTV** [comment]
Fixed in [2.9](https://www.curseforge.com/minecraft/mc-mods/exchangers/files/2903998).
