### ISSUE TITLE
Noisy Replacement

### ISSUE THREAD

**Issue by blisslen** [JackyyTV/Exchangers#63]
I'd be interested in having a mode for the exchangers which uses RNG to determine if blocks are to be replaced, with some possible control over the chance to replace block (it'd be clunky to implement that in shortcuts only, so IDK about that).

The reason for that is that, when I'm playing, I always _want_ my builds to look professional and nice, but I usually just end up building big cobble monstrosities, and then replacing cobble with, say, a nicer, chiseled kind.

What I'd really like to do is build my cobble monstrosity, and apply a couple layers of this sort of noisy replacement to give the effect of block-texturing (something like https://imgur.com/a/VAsZSYG), with minimal effort.

Honestly though, this might be a big ask, since it seems difficult to implement in a way that's reasonably easy to use.

**Comment by JackyyTV** [comment]
I think in order to implement this feature, I would have to migrate to a GUI and put all the switches in it as I am adding way too many keybinds than I originally intended to.

I must admit, this is a rather challenging feature to add since I have never worked with anything to do with GUIs before, but I can try my best, plus I could find help from other modder friends I know of if I really need to.

This is gonna take a while to implement as I'm also trying to work on a 1.14/1.15 port for this mod (and my other mods), so please bear with me.

**Comment by JackyyTV** [comment]
Finally added this in [2.10](https://www.curseforge.com/minecraft/mc-mods/exchangers/files/3174939):
![](https://user-images.githubusercontent.com/11830494/105193807-e0740a80-5b73-11eb-9bc2-9ce297884056.png)
Use the `comma` key to open the GUI, the configs for Fuzzy Placement mode are at the bottom of the GUI, the button on the left is for toggling Fuzzy Placement mode on/off while the text box on the right is for setting the placement chance, set a number between 1 and 100.
