### ISSUE TITLE
LV Exchanger breaks when you hold it and recieve damage

### ISSUE THREAD

**Issue by abunyasha12** [JackyyTV/Exchangers#64]
LV Exchanger breaks when you hold it and recieve damage i.e. fall damage
https://www.youtube.com/watch?v=9aasv8jEnfE

**Comment by JackyyTV** [comment]
Uh... That appears to be another mod in the modpack you're playing creating that strange behavior.
Just to be clear, I've never programmed anything to do with breaking the exchangers when the player takes fall damage, so that is probably done by another mod, which I have no idea what it is, you might have to check what mods you have installed and find out yourself.
